ALTER SCHEMA  GM_SF_DBT_PROJECT_DEMO_LANDING_DB.GCC_REPORTING  SET LOG_LEVEL = 'INFO';
ALTER SCHEMA  GM_SF_DBT_PROJECT_DEMO_LANDING_DB.GCC_REPORTING  SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA  GM_SF_DBT_PROJECT_DEMO_LANDING_DB.GCC_REPORTING  SET METRIC_LEVEL = 'ALL';