name: gm_snf_dbt_reporting
version: 1.0.0
config-version: 2
profile: gm_snf_dbt_reporting
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  gm_snf_dbt_reporting:
    +materialized: view
