gm_snf_dbt_reporting:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DEV_ARF_GCC_DATA_ENGINEER
      warehouse: TASTY_BYTES_DBT_WH
      database: GM_SF_DBT_PROJECT_DEMO_LANDING_DB
      schema: GCC_REPORTING
      account: ''
      user: ''
      threads : 8
